// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5IvV8uSeJm2U5Tfq7C3Snu1S_9_mm4k',
    appId: '1:471038120373:web:5550dada9b6d3e7a9a09fc',
    messagingSenderId: '471038120373',
    projectId: 'sumberwringinapp',
    authDomain: 'sumberwringinapp.firebaseapp.com',
    storageBucket: 'sumberwringinapp.appspot.com',
    measurementId: 'G-RDDHNRS81H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQb2BnTPUAAFDG_vTB-OINscH8hBE5Szk',
    appId: '1:471038120373:android:0d7cb3947deb48999a09fc',
    messagingSenderId: '471038120373',
    projectId: 'sumberwringinapp',
    storageBucket: 'sumberwringinapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgVjxV5KYWDwHMkLy7O_joW9tNU-4XUlY',
    appId: '1:471038120373:ios:7434ff9cb1fa70a39a09fc',
    messagingSenderId: '471038120373',
    projectId: 'sumberwringinapp',
    storageBucket: 'sumberwringinapp.appspot.com',
    iosClientId: '471038120373-frj0g22mtm1poguav1sj45vu5hjcm0s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPkmSw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgVjxV5KYWDwHMkLy7O_joW9tNU-4XUlY',
    appId: '1:471038120373:ios:7434ff9cb1fa70a39a09fc',
    messagingSenderId: '471038120373',
    projectId: 'sumberwringinapp',
    storageBucket: 'sumberwringinapp.appspot.com',
    iosClientId: '471038120373-frj0g22mtm1poguav1sj45vu5hjcm0s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPkmSw',
  );
}
